apiVersion: apps/v1 
kind: Deployment
metadata:
  name: soso-webapp
  labels: 
     app: webapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: webapp

  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: sosotech/webapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1